spring.datasource.url=jdbc:postgresql://localhost:5432/gym_tracker
spring.datasource.username=postgres
spring.datasource.password=aralsk2019@@POPa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

spring.datasource.hikari.maximum-pool-size=8